<?php

// autoload.php @generated by Composer(altered by Nosto Phing)

require_once dir(__FILE__) . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInit1d8b397ce2bd4e9eb888b91e7bce2229::getLoader();
